// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7VnOCiRW-xugZGE2oHwJ_yAH6M2bxPEQ',
    appId: '1:421548652647:web:cbe9e5942318927da7bcc2',
    messagingSenderId: '421548652647',
    projectId: 'orbit-bb448',
    authDomain: 'orbit-bb448.firebaseapp.com',
    storageBucket: 'orbit-bb448.firebasestorage.app',
    measurementId: 'G-QLHT8Z04XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4bC2a_-Lic6TSysHwPdKO30zcwVjYQkA',
    appId: '1:421548652647:android:58290b9453c5d0dfa7bcc2',
    messagingSenderId: '421548652647',
    projectId: 'orbit-bb448',
    storageBucket: 'orbit-bb448.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC829xZ1gBpU9ac4sb3nL60Cr2ozKfDkG4',
    appId: '1:421548652647:ios:9280b1f95b6e215ba7bcc2',
    messagingSenderId: '421548652647',
    projectId: 'orbit-bb448',
    storageBucket: 'orbit-bb448.firebasestorage.app',
    iosBundleId: 'com.example.orbit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC829xZ1gBpU9ac4sb3nL60Cr2ozKfDkG4',
    appId: '1:421548652647:ios:9280b1f95b6e215ba7bcc2',
    messagingSenderId: '421548652647',
    projectId: 'orbit-bb448',
    storageBucket: 'orbit-bb448.firebasestorage.app',
    iosBundleId: 'com.example.orbit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7VnOCiRW-xugZGE2oHwJ_yAH6M2bxPEQ',
    appId: '1:421548652647:web:5eede3fd203d6e24a7bcc2',
    messagingSenderId: '421548652647',
    projectId: 'orbit-bb448',
    authDomain: 'orbit-bb448.firebaseapp.com',
    storageBucket: 'orbit-bb448.firebasestorage.app',
    measurementId: 'G-YJ4ZVYM6HQ',
  );
}
